http.cors.allow-credentials: true
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-origin: 'http://localhost:1358'
http.cors.enabled: true
http.port: 9200
network.host: 0.0.0.0
xpack.security.authc.api_key.enabled: false
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false