version: "3.9"
services:
  es_01:
    container_name: es_01
    environment:
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es_01,es_02,es_03
      - cluster.name=es_cluster
      - discovery.seed_hosts=es_02,es_03
      - node.name=es_01
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    networks:
      - es_cluster
    ports:
      - "9200:9200"
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_01:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  es_02:
    container_name: es_02
    environment:
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es_01,es_02,es_03
      - cluster.name=es_cluster
      - discovery.seed_hosts=es_01,es_03
      - node.name=es_02
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    networks:
      - es_cluster
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_02:/usr/share/elasticsearch/data
  es_03:
    container_name: es_03
    environment:
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es_01,es_02,es_03
      - cluster.name=es_cluster
      - discovery.seed_hosts=es_01,es_02
      - node.name=es_03
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    networks:
      - es_cluster
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_03:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    networks:
      - es_cluster
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
  dejavu:
    container_name: dejavu
    depends_on:
      - es01
    image: appbaseio/dejavu
    ports:
      - "1358:1358"
    networks:
      - es_cluster

volumes:
  es_data_01:
    driver: local
  es_data_02:
    driver: local
  es_data_03:
    driver: local
  kibana_data:
    driver: local

networks:
  es_cluster:
    driver: bridge